import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: { flex: 1 },
  container: { flex: 1 },
  contentContainer: { paddingHorizontal: 20, gap: 18 },
  badgeRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  badgeLeftRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  badge: { fontSize: 11, letterSpacing: 1.8, textTransform: 'uppercase', fontWeight: '700' },
  stepPill: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  stepPillText: { fontSize: 11, fontWeight: '700' },
  headerRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  headerRightActions: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 4 },
  headerAction: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  headerGhostAction: { opacity: 0.95 },
  headerTitleWrap: { flex: 1 },
  title: { fontSize: 29, fontWeight: '800', textTransform: 'uppercase' },
  continueButton: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 9 },
  continueButtonText: { fontWeight: '800', fontSize: 13 },
  sectionCaption: { fontSize: 11, fontWeight: '700', letterSpacing: 1.2 },
  sessionTypeCard: { borderRadius: 14, borderWidth: 1, padding: 10, gap: 8 },
  sessionTypeSegment: { flexDirection: 'row', borderRadius: 12, borderWidth: 1, padding: 4, gap: 6 },
  sessionTypeOption: { flex: 1, borderRadius: 9, paddingVertical: 8, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  sessionTypeOptionSelected: { backgroundColor: '#6B46FF' },
  sessionTypeOptionText: { fontSize: 13, fontWeight: '700' },

  modeRail: { gap: 12 },
  modeCard: { borderRadius: 18, borderWidth: 1, overflow: 'hidden' },
  modeCardSelected: { shadowColor: '#6B46FF', shadowOpacity: 0.3, shadowRadius: 12, shadowOffset: { width: 0, height: 0 }, elevation: 6 },
  modeCardInner: { paddingHorizontal: 14, paddingVertical: 14, flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  modeTitle: { fontSize: 24, fontWeight: '500', marginTop: 2 },
  modeDescription: { fontSize: 13, marginTop: 4, maxWidth: 250, fontWeight: '400' },
  modeIconBubble: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' },

  optionsColumn: { gap: 10 },
  trackCard: { borderWidth: 1, borderRadius: 14, padding: 12, flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'center' },
  trackMainArea: { flex: 1, gap: 4 },
  trackTitle: { fontSize: 17, fontWeight: '700' },
  trackInfo: { fontSize: 13 },
  trackMeta: { fontSize: 12, fontWeight: '700', letterSpacing: 0.8 },
  previewButton: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, flexDirection: 'row', gap: 4, alignItems: 'center' },
  previewButtonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 12 },

  timeCard: { borderRadius: 14, borderWidth: 1, padding: 14, gap: 4 },
  timeTitle: { fontSize: 24, fontWeight: '500' },
  timeDescription: { fontSize: 13 },
  startButton: { marginTop: 4, borderRadius: 16, paddingVertical: 14, alignItems: 'center' },
  startButtonText: { fontSize: 17, fontWeight: '800' },

  sessionFullscreen: { flex: 1, backgroundColor: '#000000' },
  cameraPlaceholder: { flex: 1, justifyContent: 'space-between' },
  sessionModalCard: { marginHorizontal: 12, borderRadius: 18, overflow: 'hidden' },
  cameraPreviewLayer: { ...StyleSheet.absoluteFillObject, zIndex: 0 },
  cameraPermissionEmptyState: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 26 },
  cameraPermissionEmptyStateText: { color: '#FFFFFFCC', marginTop: 8, textAlign: 'center', fontSize: 13, fontWeight: '600' },
  recordingBackground: { backgroundColor: '#1A1A1A' },
  trainingBackground: { backgroundColor: '#14122A' },
  trainingHeader: { paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  trainingAppName: { color: '#D4CCFF', fontSize: 12, letterSpacing: 1.6, textTransform: 'uppercase', fontWeight: '700', marginBottom: 6 },
  recordingOverlayInfoBlock: { alignSelf: 'flex-start', gap: 6 },
  recordingOverlayTitleRow: { borderRadius: 16, backgroundColor: '#0000007A', borderWidth: 1, borderColor: '#FFFFFF2A', paddingHorizontal: 12, paddingVertical: 8, minWidth: 138 },
  recordingOverlayAppName: { color: '#FFFFFF', fontSize: 12, letterSpacing: 1.6, textTransform: 'uppercase', fontWeight: '700' },
  recordingOverlayTimer: { color: '#FFFFFF', fontSize: 18, alignSelf: 'flex-start', marginTop: 2 },
  trainingModeTag: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  recordingOverlayTag: { alignSelf: 'flex-start', borderRadius: 999, borderWidth: 1, borderColor: '#FFFFFF2A', paddingHorizontal: 10, paddingVertical: 6, backgroundColor: '#0000007A' },
  trainingModeTagText: { color: '#CFC5FF', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  recordingModeTagText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  trainingCenterClearSpace: { flex: 1 },
  trainingBottomArea: { gap: 12, paddingHorizontal: 12 },
  selectBeatButton: { alignSelf: 'flex-end', borderRadius: 999, paddingVertical: 10, paddingHorizontal: 14, backgroundColor: '#6B46FF', flexDirection: 'row', alignItems: 'center', gap: 8 },
  selectBeatButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  trainingPlayerBar: { borderRadius: 18, borderWidth: 1, borderColor: '#FFFFFF20', backgroundColor: '#00000099', paddingVertical: 12, paddingHorizontal: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  trainingTrackMeta: { flex: 1, gap: 2 },
  trainingTrackTitle: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  trainingTrackSub: { color: '#B3B3C4', fontSize: 12, fontWeight: '600' },
  trainingPlayerControls: { flexDirection: 'row', gap: 8 },
  trainingControlButton: { width: 38, height: 38, borderRadius: 19, borderWidth: 1, borderColor: '#FFFFFF26', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF14' },
  sessionHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  timer: { fontSize: 20, fontWeight: '800', color: '#FFFFFF' },
  finishButton: { borderRadius: 999, backgroundColor: '#0000007A', paddingHorizontal: 16, paddingVertical: 10 },
  finishButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  preSessionActionsRow: { width: '100%', alignItems: 'center', justifyContent: 'center', position: 'relative', gap: 10 },
  recordingConfigCard: { position: 'absolute', top: -112, width: '66%', alignSelf: 'center', borderRadius: 12, borderWidth: 1, borderColor: '#FFFFFF24', backgroundColor: '#050505AB', paddingVertical: 8, paddingHorizontal: 10, gap: 6 },
  recordingConfigTitle: { color: '#FFFFFF', fontSize: 11, fontWeight: '700', textAlign: 'center' },
  recordingConfigActions: { flexDirection: 'row', justifyContent: 'center' },
  recordingConfigActionButton: { borderRadius: 10, borderWidth: 1, borderColor: '#FFFFFF20', backgroundColor: '#FFFFFF12', paddingVertical: 7, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  recordingConfigActionText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  recordPreControlsRow: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 52 },
  preRecordSideButton: { width: 54, height: 54, borderRadius: 27, borderWidth: 1, borderColor: '#FFFFFF3A', backgroundColor: '#0000007A', alignItems: 'center', justifyContent: 'center' },
  bottomSwitchCameraButton: { alignItems: 'center', gap: 2, padding: 8 },
  bottomSwitchCameraButtonBeforeStart: { position: 'absolute', left: '50%', marginLeft: 58 },
  bottomSwitchCameraDisabled: { opacity: 0.4 },
  overlayWordWrapper: { alignSelf: 'center', marginTop: 'auto', marginBottom: 10, borderRadius: 16, borderWidth: 1, borderColor: '#FFFFFF33', backgroundColor: '#00000088', paddingVertical: 14, paddingHorizontal: 22, alignItems: 'center', maxWidth: '85%' },
  overlayWordLabel: { color: '#FFFFFFB3', fontSize: 11, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6 },
  overlayWordValue: { color: '#FFFFFF', fontSize: 36, fontWeight: '900', textAlign: 'center' },
  sessionBottomActions: { alignItems: 'center', justifyContent: 'center', minHeight: 150 },
  recordButton: { width: 86, height: 86, borderRadius: 43, borderWidth: 4, borderColor: '#FFFFFFAA', justifyContent: 'center', alignItems: 'center' },
  recordButtonInner: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#EF4444' },
  liveSessionSwitchCameraButton: { width: 86, height: 86, borderRadius: 43, borderWidth: 1, borderColor: '#FFFFFF33', backgroundColor: '#0000007A', alignItems: 'center', justifyContent: 'center' },
  countdownNumber: { fontSize: 82, fontWeight: '800' },
  baseModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: '#000000A6', justifyContent: 'center', paddingHorizontal: 18, zIndex: 20 },
  baseModalCard: { borderRadius: 20, borderWidth: 1, borderColor: '#FFFFFF1F', backgroundColor: '#121022', padding: 14, gap: 12, maxHeight: '70%' },
  baseModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  baseModalTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '800' },
  baseModalClose: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#FFFFFF1A', alignItems: 'center', justifyContent: 'center' },
  baseOptionsColumn: { gap: 8 },
  baseOptionItem: { borderRadius: 12, borderWidth: 1, borderColor: '#FFFFFF1F', backgroundColor: '#FFFFFF0A', padding: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  baseOptionSelected: { borderColor: '#6B46FF', backgroundColor: '#6B46FF22' },
  baseOptionMain: { gap: 2 },
  baseOptionTitle: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
  baseOptionDesc: { color: '#BDB7E5', fontSize: 12, fontWeight: '600' },

  summaryScreen: { flex: 1, paddingHorizontal: 20, paddingVertical: 16, gap: 16 },
  summaryHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  summaryTitle: { fontSize: 22, fontWeight: '800' },
  summaryCloseButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  summaryMetaCard: { borderRadius: 14, borderWidth: 1, padding: 14, gap: 6 },
  summaryMetaText: { fontSize: 14, fontWeight: '600' },
  summaryMetaDescription: { fontSize: 13, fontWeight: '500' },
  previewCard: { gap: 8 },
  previewVideo: { height: 320, borderRadius: 16, borderWidth: 1, justifyContent: 'flex-start', alignItems: 'flex-start', padding: 14, overflow: 'hidden' },
  previewVideoPlayer: { ...StyleSheet.absoluteFillObject },
  previewThumbnail: { position: 'absolute', right: 14, bottom: 14, width: 78, height: 78, borderRadius: 10, borderWidth: 1, borderColor: '#FFFFFF88' },
  previewOverlayChip: { position: 'absolute', left: 14, top: 14, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: '#00000099', flexDirection: 'row', alignItems: 'center', gap: 5 },
  previewOverlayChipText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  previewHint: { fontSize: 12 },
  summaryActions: { flexDirection: 'row', gap: 10, marginTop: 'auto' },
  summaryActionButton: { flex: 1, borderRadius: 12, paddingVertical: 12, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  summaryActionText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
});


export default styles;
